services:
  jkh-postgres:
    image: postgres:16
    container_name: jkh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jkh
      POSTGRES_PASSWORD: jkh_password_change_me
      POSTGRES_DB: jkh_smartfarm
    ports:
      - "5432:5432"
    volumes:
      - jkh_pgdata:/var/lib/postgresql/data

volumes:
  jkh_pgdata:

